PLAT-40278 : Add background circle in Checkbox
enyojs/moonstone pull request #2943
Opened 2017-05-11 05:26 UTC by changgilee

Add background circle base on `18 GUI guidance in Enyo.

Enyo-DCO-1.1-Signed-off-by: Changgi Lee <changgi.lee@lge.com>

2017-06-12 05:44 UTC, yeram commented on src/Checkbox/Checkbox.less
> +		border-radius: 15px;
Based on enact we also need `line-height` as `30px` and `font-size` as `60px`.

2017-06-12 21:54 UTC, Djspaceg requested changes
Let's make a few organizational changes to this PR.

2017-06-12 21:54 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +		height: 30px;
These would probably be better as a `@moon-checkbox-size` variable in the `variables.less` file

2017-06-12 21:54 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +		font-size: 60px;
This line could become `font-size: (@moon-checkbox-size * 2);`

2017-06-12 21:54 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +		border-radius: 15px;
This line could become `font-size: (@moon-checkbox-size / 2);`

2017-06-12 21:54 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +		background-color: @moon-dark-gray;
It's best practice to not refer to these variables outside of the `moonstone-dark/light.less` files, and instead assign the `@moon-dark-gray` to a more descriptive color variable name, like `@moon-checkbox-bg-color: @moon-dark-gray;`. This is simpler and easier to maintain over time and abstracts the color value from the component LESS files. Be sure to update both the light and dark color files.

2017-06-12 21:54 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +			background-color: rgba(255,255,255,0.41);
This should be a color variable too. Also, do you think anyone can notice the difference between `0.41` and `0.4` alpha levels? Let's go ahead and round this value down to `0.4`: `rgba(255,255,255,0.4)`.
Alternatively, in the color file, you could use the LESS function to apply the alpha as well: `fade(@moon-white, 40%)`

2017-06-13 23:35 UTC, Djspaceg commented on src/Checkbox/Checkbox.less
> +			color: @moon-white;
Each of these `@moon-white` variables should be updated to be `@moon-spotlight-text-color`. This one, line 67, and 46.

2017-06-14 05:52 UTC, merged